
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch To Merge
        required: true

permissions:
  # Allows us write to the repo
  contents: write

jobs:
  merge_branch:
    name: Merge Branch
    runs-on: ubuntu-20.04
    environment: release
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Download Github Release
        run: |
          set -x
          git merge --ff-only origin/${{ github.event.inputs.branch }}
          git push
