name: Verify Installation

permissions:
  contents: read

on: [workflow_dispatch, pull_request, push]

jobs:
  verify_homebrew_macos_14:
    name: MacOS 14
    runs-on: macos-14
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install Ockam
        run: |
          set -e

          brew install build-trust/ockam/ockam
          ockam --version

          ls -l /opt/homebrew/etc/bash_completion.d/ockam

          echo "Ockam was successfully installed via Homebrew on MacOS 14." | tee -a $GITHUB_STEP_SUMMARY

  verify_homebrew_ubuntu_22_04:
    name: Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install Ockam
        run: |
          set -e

          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install build-trust/ockam/ockam
          ockam --version

          ls -l /home/linuxbrew/.linuxbrew/etc/bash_completion.d/ockam

          echo "Ockam was successfully installed via Homebrew on Ubuntu 22.04." | tee -a $GITHUB_STEP_SUMMARY
